### ISSUE TITLE
Arguments to path.join must be strings

### ISSUE THREAD

**Issue by gavD** [christophercliff/wintersmith-kelvin#7]
I've followed the [docs](https://github.com/christophercliff/wintersmith-kelvin) and I get:

```
  building site
  using config file: /private/var/www/radify.io/ui/static/config.json

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
        ^
TypeError: Arguments to path.join must be strings
  at path.js:360:15
  at Array.filter (native)
  at Object.exports.join (path.js:358:36)
  at Function.KelvinJavaScripts.fromFile (/private/var/www/radify.io/ui/static/node_modules/wintersmith-kelvin/lib/plugin.coffee:97:7)
  at loadContent (/usr/local/lib/node_modules/wintersmith/lib/core/content.js:182:28)
  at /usr/local/lib/node_modules/wintersmith/lib/core/content.js:312:22
  at fn (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:582:34)
  at Object._onImmediate (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:498:34)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Here is my package.json:

```json
{
  "dependencies": {
	"wintersmith-less": "*",
	"wintersmith-nunjucks": "*",
	"underscore": "*",
	"wintersmith-kelvin": "*",
	"wintersmith": "*",
	"wintersmith-tag": "*",
	"moment": "*"
  }
}
```

do I have the wrong version of some dependency or something? Would appreciate any tips!

**Comment by CmdrNopileos** [comment]
I encounter the same problem. Any ideas on how to resolve that?

**Comment by gavD** [comment]
Hi @CmdrNopileos, I came to the conclusion that wintersmith-kelvin isn't compatible with the current verison of Wintersmith. Please see https://github.com/jnordberg/wintersmith/wiki/Plugins for details.

**Comment by christophercliff** [comment]
FYI, I won't be making any updates to this plugin in the future. Suggest you fork or find alternative.
